### ISSUE TITLE
Add extra detail to team work contract

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/global_warming_effects_on_ice_thickness#24]
From https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md: 

- How will work be distributed in a fair and equitable way?
- How often will group meetings occur?
- Will you have meeting agendas and minutes? If so, what will be the system for rotating through these responsibilities?
- What will be the style of working?
- Will you start each day with stand-ups, or submit a summary of your contributions 4 hours before each meeting? or something else?
- What is the quality of work each team member expects from themselves and each other?

**Comment by mgaroub** [comment]
I don't think we should answer this individually. We can enhance the contract next week.

**Comment by sbabicki** [comment]
Yeah, they are just suggested things to include. I added a section for meeting cadance and team member responsibility so now I feel like we have enough.
