### ISSUE TITLE
Script 3 - Create EDA

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/global_warming_effects_on_ice_thickness#30]
A third script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that dataset. This should take two arguments:
a path/filename pointing to the data
a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png)

**Comment by syadk** [comment]
Create :
bar chart with time(specific month of every year) on the x-axis and median value of station averages on y-axis
histogram (plot for the two specific months) each showing distribution of ice thickness averages -> count of observations on y-axis and mean station values for that month on x-axis
