### ISSUE TITLE
Update README for Milestone 2

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/global_warming_effects_on_ice_thickness#35]
- In the main README.md file for this project you should explain the project in a short summary (view from 10,000 feet) and also explain how to run your data analysis (which order scripts are run in, what expected inputs are). Your explanation could include a flow chart/dependecy diagram. This should be an evolution of what was submitted at the proposal stage. Yes, we are asking you to overwrite your proposal here, and so if you want to keep that in a more findable place than in the Git history, do create a new file in the doc directory to archive it there (e.g., proposal.md).

- List the software dependencies for your analysis in the README (or if you use conda, point to the environment.yml file)

**Comment by sbabicki** [comment]
As per Tiff in lab2: move proposal out of README and replace with highlevel overview

**Comment by sbabicki** [comment]
The dependencies are updated now!

**Comment by mgaroub** [comment]
Done.
