### ISSUE TITLE
Update report to discuss extending analysis to other months and years

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/global_warming_effects_on_ice_thickness#57]

**Comment by sbabicki** [comment]
I'm planning to ask a TA how to approach this in the lab this week.

**Comment by sbabicki** [comment]
As per Tiff: we don't have the method yet to analyze multiple p-values or time series. Instead of updating analysis, update the report to mention that we would be interested in exploring that in future studies. It might also be good to refer to the seasonal trends in the histogram for the months and CIs for the years.

**Comment by mgaroub** [comment]
Added the new references to the Rmd. to match .bib
