### ISSUE TITLE
Fix density.svg plot

### ISSUE THREAD

**Issue by jaymegordo** [UBC-MDS/global_warming_effects_on_ice_thickness#68]
density plot is failing to save data:
```
WARN Ignoring an invalid transform: {"as":["mean_ice_thickness","density"],"density":"mean_ice_thickness","groupby":["year","month"]}.
WARN Infinite extent for field "density": [Infinity, -Infinity]
WARN Ignoring an invalid transform: {"as":["mean_ice_thickness","density"],"density":"mean_ice_thickness","groupby":["year","month"]}.
WARN Infinite extent for field "density": [Infinity, -Infinity]
WARN facet encoding should be discrete (ordinal / nominal / binned).
```

**Comment by sbabicki** [comment]
I'm getting the same error. The current work-around has the report referring to density.jpg which is saved manually. Hopefully at the next milestone we can get it to work with docker.

**Comment by sbabicki** [comment]
Fixing this graph was also suggested in peer feedback:
#91 
Another suggestion is that perhaps you can increase the font of title and axis titles for your Figure 2. Distribution of Ice Thickness by Month from the report so that the figure would be more readable.

**Comment by sbabicki** [comment]
Also mentioned in 
#92 
Only one exception was that the density.svg plot didn't properly render.

**Comment by jufu** [comment]
(while I was googling for this issue, this issue log came up)

We encountered a similar issue but 1 of the density plots didn't render/save properly.  Just fixed it in the Dockerfile by forcing pandas =1.1.5 .  

We were using the base container jupyter/scipy-notebook, which is on 1.1.4.

Probably not the same issue, but worth a shot!
