### ISSUE TITLE
Create milestone 4 release and submit to Canvas

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/global_warming_effects_on_ice_thickness#79]
You must include the URL of your public project's repository in your milestone 4 submission on Canvas, so we know where to find it.
Just before you submit the milestone 4, create a release on your project repository on GitHub and name it 0.3.0. Include the URL to this release in your milestone 4 submission on Canvas, so we can easily jump to the state of your repository at the time of submission for grading purposes, while you continue to work on your project for the next milestone.

**Comment by mgaroub** [comment]
Done
