### ISSUE TITLE
Test Dockerfile

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/global_warming_effects_on_ice_thickness#80]
Someone not responsible for creating the file should test running it from scratch.

**Comment by jaymegordo** [comment]
Everything ran great for me the first time. Only two commands I ran were:
- `docker pull syadk/ice-thickness`
- `docker run  -it --rm -v $(pwd):/home/ice_thickness syadk/ice-thickness:v0.3.0 make -C /home/ice_thickness all`
