### ISSUE TITLE
Create fork on personal account, update UBC-MDS repo only through pull requests

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/global_warming_effects_on_ice_thickness#9]
Just a reminder! Once everyone has sent their first pull request we can close this issue.

**Comment by sbabicki** [comment]
@jaymegordo you created your own fork, right? Yours is the only one I'm not seeing, did you make it private?  
![image](https://user-images.githubusercontent.com/1518873/99885916-46ccc300-2bed-11eb-96bd-c39f0a2fd45b.png)

**Comment by jaymegordo** [comment]
Created mine!
