### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by zhijingjing1** [UBC-MDS/global_warming_effects_on_ice_thickness#91]
Hello team 13, I enjoy reading the reports and EDA you created and learn much from it. Here are a few minor points of feedback that I hope can be helpful for you.

Your project documentation is very clear and easy to understand. The code looks good and readable. One suggestion is that perhaps you can consider to put your final report to a separate directory so it might be more convenient for a reader to find it. Another suggestion is that perhaps you can increase the font of title and axis titles for your Figure 2. Distribution of Ice Thickness by Month from the report so that the figure would be more readable.

Overall, I want to say “Good job!” to you guys. Thanks for presenting us this awesome data analysis project!

**Comment by sbabicki** [comment]
Thanks for your feedback Jingjing!

**Comment by mgaroub** [comment]
Thank you Jingjing.
