### ISSUE TITLE
Peer feedback - Aidan

### ISSUE THREAD

**Issue by aidanmattrick** [UBC-MDS/global_warming_effects_on_ice_thickness#92]
Hey all,

Here are my impressions from reviewing and building your project:

**Documentation:**
Very clear and well laid out. Only comment I would have is that generated files (i.e. graphs) already exist in the repo so if one wants to build, they should run make clean first. This could be made a bit more clear.

**Code:**
Readable and reproducible. Only one exception was that the density.svg plot didn't properly render.

**Analysis & Reasoning:**
Thought you did a good job here. The only thing I was curious about that I would have liked to hear about is what your thoughts are with the outlier in the dataset of the year 2002. I know this is outside the scope of the question but since this data point was included I was curious for your interpretation.

Maybe consider putting this section in a separate reports directory instead of in docs but this might be more of a subjective criticism than an objective one. One additional thing I thought might be helpful (if possible) is a brief overview of the different stations involved in data collection (i.e. number and location).

**Communication:**
Nothing really stood out to me as needing improvement here. Well written and easy to read/follow along with. Only thing I might suggest is adding some more information around seasonality piece. I am uncertain as to how seasonality is not taken into account given that data was collected at the same time each year.

**Comment by sbabicki** [comment]
Thank you for your feedback, Aidan!
